### ISSUE TITLE
AttributeError while parsing

### ISSUE THREAD

**Issue by Geize** [rvhonorato/cazy-parser#11]
Hi Rodrigo, 

I still have a problem with the script. Could you take a look? Thanks in advance. 

![cazy_parser](https://user-images.githubusercontent.com/7786478/52358149-694d1680-2a2f-11e9-815d-f7993516dfd8.png)

**Comment by rvhonorato** [comment]
Thanks for reporting, this is caused by new entries that to not have Genbank code. Working on a fix and checking consistency, this might take a while @Geize.

**Comment by rvhonorato** [comment]
fixed (#12) and created a new release
