### ISSUE TITLE
fail on create_cazy_db 

### ISSUE THREAD

**Issue by jtamames** [rvhonorato/cazy-parser#13]
Hello,
When using create_cazy_db, it fails with the following error:

> Gathering species with full genomes
 Elapsed Time: 0:00:00 N/A% [                                                                                                                   ] ETA:  --:--:-- Traceback (most recent call last):
  File "/usr/local/bin/create_cazy_db", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/cazy_parser/create_cazy_db.py", line 292, in main
    species_dic = fetch_species()
  File "/usr/local/lib/python2.7/dist-packages/cazy_parser/create_cazy_db.py", line 69, in fetch_species
    f = urllib.request.urlopen(link)
AttributeError: 'module' object has no attribute 'request'

Am I missing something?
Thanks for developing this!
Best,

**Comment by lucaz88** [comment]
Did anyone got around this issue? 
I just had the same issue today, I have tried using Python 3.6 and 3.8 env without success. 
Cheers!

**Comment by rvhonorato** [comment]
Hi, sorry for the extreme long delay in replying to this 😁 

This error seems to be relate do you using python2.7 whereas cazy-parser need python3.

**Comment by rvhonorato** [comment]
I've just released a new version, please try using that one instead! (:
