### ISSUE TITLE
Errors occurred using pip installation

### ISSUE THREAD

**Issue by bj600800** [rvhonorato/cazy-parser#18]
Thanks for your recently update for this repo. It is very very helpful.
Additionally, I encountered an error while installing the pkg using pip followed README. It shows bellow,
1. CANNOT call 'cazy-parser' using bash command.
2. --upgrade flag cannot procced pkg upgrading.

Fortunately, I used configure and install from setup.py worked successfully.
Maybe it is not an critical error, just want to leave a note.
Again, thank you for your great work!

**Comment by rvhonorato** [comment]
Thanks for reporting it and for the feedback 🎉 , I'll have a look!

**Comment by rvhonorato** [comment]
The issue was that I forgot to push v2.0.0 to pypi, so it was still pulling old v1.4.2 😅 

https://pypi.org/project/cazy-parser/2.0.0/

Should be working now, thanks again @bj600800
