### ISSUE TITLE
Retrieve only the experimentally characterized cazy?

### ISSUE THREAD

**Issue by BinhongLiu** [rvhonorato/cazy-parser#42]
Hi, 
I want to retrieve only the experimentally characterized cazy. Was the `-c CHARACTERIZED` argument set for this? I'm not sure how to set this argument since whether or not add `-c True` does not affect the downloaded number of sequences.
Thanks! 
![image](https://github.com/rvhonorato/cazy-parser/assets/35453307/346b2c6b-d026-430b-969b-f8af5993d543)

**Comment by rvhonorato** [comment]
Thanks for reaching out @BinhongLiu. 

Well spotted! It seems the `CHARACTERIZED` argument is indeed not used when the genbank ids are retrieved, oops 😅 

I'll patch it up and let you know once its fixed

**Comment by rvhonorato** [comment]
I've updated the version to account for this missing option, see the difference below:
```
$ cazy-parser GH -f 43 -s 1
# ...

$ cat GH43_1_12102023.fasta| grep ">" | wc -l
1781

$ cazy-parser GH -f 43 -s 1 -c
# ...

$ cat GH43_1_characterized_12102023.fasta| grep ">" | wc -l
23
```

Please update your version to 2.0.3 with `pip install --upgrade cazy-parser` and let me know if you run into any other issues 🤓
