### ISSUE TITLE
not all members extracted

### ISSUE THREAD

**Issue by geo80** [rvhonorato/cazy-parser#6]
Hi Rodrigo,
I tried to extract a few families and I noticed that out of e.g. 3000 entries in CAZy, I only get 250 when I run cazy-parser.
Is that the expected behavior?

Thanks,
George

**Comment by rvhonorato** [comment]
Could you please give more details? Which class and which family?

**Comment by rvhonorato** [comment]
Closed since there is not enough information to replicate.
