### ISSUE TITLE
port to Python 3.x?

### ISSUE THREAD

**Issue by phiweger** [rvhonorato/cazy-parser#9]
great library, and a couple of brackets should make it compatible w/ Python 3

**Comment by rvhonorato** [comment]
Should be easy to port, thanks for the suggestion.

**Comment by xuechunxu** [comment]
Hi,

I got an error:Traceback (most recent call last):
  File "/home/xuechunxu/miniconda2/bin/create_cazy_db", line 11, in <module>
    sys.exit(main())
  File "/home/xuechunxu/miniconda2/lib/python2.7/site-packages/cazy_parser/create_cazy_db.py", line 112, in main
    soup = BeautifulSoup(urllib.urlopen(main_class_link), "lxml")
  File "/home/xuechunxu/miniconda2/lib/python2.7/site-packages/bs4/__init__.py", line 198, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

Wish you response soon!

Chunxu

**Comment by rvhonorato** [comment]
Greetings @xuechunxu , please update to the latest version.

**Comment by rvhonorato** [comment]
> great library, and a couple of brackets should make it compatible w/ Python 3

Updated to Python 3.6.
